services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  FluidTYPO3\TestProviderExtension\Controller\:
    resource: '../Classes/Controller/*'
    autowire: true
    public: true
